== `dotnet_pkg_info` Tool
:numbered:

=== Introduction

Microsoft _.NET core_ is a cross-platform framework that can be used to build ASP.NET Core web applications, command-line applications, libraries, and universal windows platform applications. The .NET applications are written in _C#, F#, or Visual Basic_ programming languages. .NET applications mainly use https://docs.com/en-us/visualstudio/msbuild/msbuild-reference[MSBuild] as the build system. The _MSBuild_ files, commonly referred as _project files_ adhere to https://docs.com/en-us/visualstudio/msbuild/msbuild-project-file-schema-reference[MSBuild XML schema]. These _project files_ end with extensions `.csproj`, `.vbproj` or `.fsproj`. .NET packages that use _Microsoft Visual Studios_ for development have a https://docs.com/en-us/visualstudio/extensibility/internals/solution-dot-sln-file[Visual Studios Solution] file (`.sln` extension) in the package root directories.  A visual studios _solution_ files for a package is a text file that has information such as _project_ file paths and _build configurations_ (`Debug` or `Release`) for the modules in the project.

Given a .NET package, `dotnet_pkg_info` is a _command line_ tool that obtains information relevant to SWAMP about the package. The tool is intended to be used by SWAMP UI team to help users add .NET packages to SWAMP. Code from `dotnet_pkg_info` tool will also be used in the SWAMP backend to get information about the package during the build.

// `dotnet_pkg_info` tool has _command line options_ to generate output in `json` and `text` format.

List of functionality of `dotnet_pkg_info`

. List _Visual Studios Solution Files_, _Project Files_, _Target Frameworks_ and _Build Configuration_ in a given package
. Show common .NET _File Type Extensions_
. Show _Target Frameworks_ on a SWAMP platform

=== List _Visual Studios Solution Files_, _Project Files_, _Target Frameworks_ and _Build Configuration_ in a given package.

Given the path to an unarchived package as an argument, The `dotnet_pkg_info` tool, starting in the project root directory (this is selected by the user), recursively looks for files with `.sln` extension . The files with `.sln` extension are  https://docs.com/en-us/visualstudio/extensibility/internals/solution-dot-sln-file?view=vs-2017[Visual Studios Solution Files]. These solution files are text based files that contain paths to https://docs.com/en-us/dotnet/core/tools/project-json-to-csproj[Dotnet Project Files] along with information such as build configurations (`Debug`, `Release`) for each of the modules. The argument can also be the path to a _solution_ file or a _project_ file.

.NET ecosystem lets packages to use APIs that are platform specific. Example: A _GUI_ application for Windows platform requires APIs only available on Windows. In .NET ecosystem this is referred as _targeting a framework_. When an application targets a particular framework or a set of frameworks, the _project_ file for that application must define `TargetFramework` or `TargetFrameworks` attribute whose values are one or more `Target Framework Moniker (TFM)` in <<table-1,Table 1>>.

[[table-1]]
.Valid Target Framework and Target Framework Moniker:
[width="80%",cols="l,l,d",options="header",style="literal"]
|==========================
| Target Framework |	Target Framework Moniker | Windows Only
| .NET Standard	|netstandard1.0
netstandard1.1
netstandard1.2
netstandard1.3
netstandard1.4
netstandard1.5
netstandard1.6
netstandard2.0 | False
| .NET Core	|netcoreapp1.0
netcoreapp1.1
netcoreapp2.0
netcoreapp2.1 |  False
| .NET Framework	|net11
net20
net35
net40
net403
net45
net451
net452
net46
net461
net462
net47
net471
net472 |  True
|Windows Store	|netcore [netcore45]
netcore45 [win] [win8]
netcore451 [win81] |  True
| .NET Micro Framework	|netmf |  True
| Silverlight	|sl4
sl5 | True
| Windows Phone	|wp [wp7]
wp7
wp75
wp8
wp81
wpa81 | True
| Universal Windows Platform	|uap [uap10.0]
uap10.0 [win10] [netcore50] | False
|==========================

This list may be change, refer to [https://docs.com/en-us/dotnet/standard/frameworks] for the update list.

To get SWAMP related information about a package, execute `dotnet_pkg_info` with `--package` option, along with the path to a package directory or a solution file or a project file. If the argument is a package directory, `dotnet_pkg_info` recursively searches for _solution_ files in the package. For each of the _solution files_, it lists the _project files_. And for each of the _project files_, `dotnet_pkg_info` list the given _target frameworks_ and _build configurations_. The options and arguments for `dotnet_pkg_info` are listed in <<dotnet-pkg-info-options,Table-2>>

[[dotnet-pkg-info-options]]
.dotnet_pkg_info Options and Arguments:
[width="80%",cols="l,d",options="header",style="literal"]
|==========================
| Option |	Description
| --package PACKAGE | Path to the package directory or a solution file or a project file
| --format FORMAT | the values `text` or `json`. Default is `json`
| --no-config | Do not display configuration information
| --no-framework | Do not display target framework information
| --src-file-types | list of .NET source file extensions
| --framework-types | list of frameworks available on
| --proj-file-types | list of .NET msbuild project file extensions
|==========================


.Example
```
% dotnet_pkg_info --package './Identity-2.0.1'
```

.Output
[%autofit]
```
{
  "sln_files": {
    "Identity.sln": [
      "src/AspNetCore.Identity/AspNetCore.Identity.csproj",
      "src/Extensions.Identity.Core/Extensions.Identity.Core.csproj"
    ],
    "IdentityCore.sln": [
      "src/AspNetCore.Identity/AspNetCore.Identity.csproj",
      "src/Extensions.Identity.Core/Extensions.Identity.Core.csproj",
      "src/Extensions.Identity.Stores/Extensions.Identity.Stores.csproj"
    ]
  },
  "proj_files": {
    "src/AspNetCore.Identity/AspNetCore.Identity.csproj": {
      "frameworks": ["netcoreapp2.0", "net461"],
      "configuration": ["Debug", "Release"],
      "default_framework": "netcoreapp2.0",
      "default_configuration": "Debug"
    },
    "src/Extensions.Identity.Core/Extensions.Identity.Core.csproj": {
      "frameworks": ["netstandard2.0"],
      "configuration": ["Debug", "Release"],
      "default_framework": "netstandard2.0",
      "default_configuration": "Debug"
    },
    "src/Extensions.Identity.Stores/Extensions.Identity.Stores.csproj": {
      "frameworks": ["netstandard2.0"],
      "configuration": ["Debug", "Release"],
      "default_framework": "netstandard2.0",
      "default_configuration": "Debug"
    }
  }
}
```

.Example with Text Output:

```
% dotnet_pkg_info --format text --package './Identity-2.0.1'
```

.Output
```
sln_files:
  Identity.sln
    src/AspNetCore.Identity/AspNetCore.Identity.csproj
    src/Extensions.Identity.Core/Extensions.Identity.Core.csproj
  IdentityCore.sln
    src/AspNetCore.Identity/AspNetCore.Identity.csproj
    src/Extensions.Identity.Core/Extensions.Identity.Core.csproj
    src/Extensions.Identity.Stores/Extensions.Identity.Stores.csproj
proj_files:
  src/AspNetCore.Identity/AspNetCore.Identity.csproj
    frameworks:
      netcoreapp2.0
      net461
    configuration:
      Debug
      Release
    default_framework:
      netcoreapp2.0
    default_configuration:
      Debug
  src/Extensions.Identity.Core/Extensions.Identity.Core.csproj
    frameworks:
      netstandard2.0
    configuration:
      Debug
      Release
    default_framework:
      netstandard2.0
    default_configuration:
      Debug
  src/Extensions.Identity.Stores/Extensions.Identity.Stores.csproj
    frameworks:
      netstandard2.0
    configuration:
      Debug
      Release
    default_framework:
      netstandard2.0
    default_configuration:
      Debug
```

NOTE: To get package information without _Build Configuration_ and _Target Framework_ information, use `--no-config` and `--no-framework` option to the `dotnet_pkg_info` command.

==== For packages without solution files

If a package does not have a _solution file_ in the package root directory, the tool recursively searches the package for _project files_. It lists the  _project files_ along with _target frameworks_ mentioned in the _project files_. Note that _build configuration_ information won't be available in this case as _build configuration_ is provided in the _solution files_.

=== Target Frameworks on SWAMP platforms

To display _target frameworks_ available on a SWAMP platform, use '--framework-types' option with `dotnet_pkg_info` tool.

.Example
```
dotnet_pkg_info --framework-types
```

Output
```
{
  ".NET Standard": {
      "tf_moniker" : [
          "netstandard1.0",
          "netstandard1.1",
          "netstandard1.2",
          "netstandard1.3",
          "netstandard1.4",
          "netstandard1.5",
          "netstandard1.6",
          "netstandard2.0",
          "netcoreapp1.0",
          "netcoreapp1.1",
          "netcoreapp2.0",
          "netcoreapp2.1"
      ],
      "windows_only": false
   },
  ".NET Core" : {
     "tf_moniker" : [
         "netcoreapp1.0",
         "netcoreapp1.1",
         "netcoreapp2.0",
         "netcoreapp2.1"
     ],
     "windows_only": false
   },
   ".NET Framework" : {
     "tf_moniker" : [
        "net11",
        "net20",
        "net35",
        "net40",
        "net403",
        "net45",
        "net451",
        "net452",
        "net46",
        "net461",
        "net462",
        "net47",
        "net471",
        "net472"
     ],
     "windows_only": true
   },
   "Windows Store": {
     "tf_moniker" : [
        "netcore [netcore45]",
        "netcore45 [win] [win8]",
        "netcore451 [win81]"
     ],
     "windows_only": true
   },
   ".NET Micro Framework": {
     "tf_moniker" : [
        "netmf"
     ],
     "windows_only": true
   },
   "Silverlight": {
     "tf_moniker" : [
        "sl4",
        "sl5"
     ],
     "windows_only": true
   },
   "Windows Phone": {
     "tf_moniker" : [
        "wp [wp7]",
        "wp7",
        "wp75",
        "wp8",
        "wp81",
        "wpa81"
     ],
     "windows_only": true
   },
   "Universal Windows Platform": {
     "tf_moniker" : [
        "uap",
        "uap10.0"
     ],
     "windows_only": false
   }
}
```

=== Show .NET File Extensions

Lists the .NET file types extensions

.Example
```
% dotnet_pkg_info --src-file-types
```

Output
```
{
  ".cs": {
    "description": "C# source files",
    "windows_only": false
  },
  ".vb": {
    "description": "Visual Basics source files",
    "windows_only": true
  },
  ".fs": {
    "description": "F# source files",
    "windows_only": true
  }
}
```

=== Show .NET Project File Extensions

Lists the .NET project file extensions

```
% dotnet_pkg_info --project-file-types
```

Output
```
{
  ".csproj": {
    "description": "csharp project file"
  },
  ".vbproj": {
    "description": "Visual Basics project files"
  },
  ".fsproj": {
  "description": "fsharp project file"
  }
}
```

=== Package info to the backend
If a user selects a _solution_ file, and a certain set of _project_ files and _target_ frameworks and _build_ configuration for their package. The SWAMP UI or middleware should pass the .NET package information to the backend in a `json` format. The information in the `json` format must be assigned to the `package-dotnet-info` attribute in the `package.conf` file.

The format for the `package-dotnet-info` should be same as the `json` output produced by `dotnet_pkg_info` tool, except for the values for `framework` and `configuration` attributes should be a single string value and not a list of string, and attributes `default_framework` and `default_configuration` should not be present.

.Example:
```
{
  "sln_files": {
    "Identity.sln": [
      "src/AspNetCore.Identity/AspNetCore.Identity.csproj",
      "src/Extensions.Identity.Core/Extensions.Identity.Core.csproj"
    ],
  },
  "proj_files": {
    "src/AspNetCore.Identity/AspNetCore.Identity.csproj": {
      "framework": "netcoreapp2.0",
      "configuration": "Debug",
    },
    "src/Extensions.Identity.Core/Extensions.Identity.Core.csproj": {
      "framework": "netstandard2.0",
      "configuration": "Debug"
    },
  }
}
```

.Scenario 1:
User selects a _solution_ but does not select projects and does not configure the projects. In this case, `package-dotnet-info` can list the _solution_ file with empty list for projects. The _assessment framework_ invokes the MSBuild system with the _solution_ file as the argument. i.e. all the modules in the _solution_ file will be built against frameworks and default configuration provided in the _project_ files for all the modules.

Example:

```
{
  "sln_files": {
    "Identity.sln": []
  }
}
```

.Scenario 2:
User selects a _solution_, and one or more projects in the _solution_, but does not select _configuration_ for the projects. In this case, `package-dotnet-info` can list the _solution_ file with the list of projects selected by the user. The _assessment framework_ invokes the MSBuild system for each of the selected projects. The projects will be built against frameworks and default configuration provided in the selected _project_ files.

Example:

```
{
  "sln_files": {
    "Identity.sln": [
      "src/AspNetCore.Identity/AspNetCore.Identity.csproj",
      "src/Extensions.Identity.Core/Extensions.Identity.Core.csproj"
    ]
  },
  "proj_files": {
    "src/AspNetCore.Identity/AspNetCore.Identity.csproj": {
    },
    "src/Extensions.Identity.Core/Extensions.Identity.Core.csproj": {
    },
  }
}
```

.Scenario 2:
User selects a _solution_, and one or more projects in the _solution_, and also selects _frameworks_ and _configuration_ for the projects. The _assessment framework_ invokes the MSBuild system for each of the selected projects. The projects will be built against framework and configuration provided by the user.

Example:

```
{
    "src/AspNetCore.Identity/AspNetCore.Identity.csproj": {
      "framework": "netcoreapp2.0",
      "configuration": "Debug"
    },
    "src/Extensions.Identity.Core/Extensions.Identity.Core.csproj": {
      "framework": "netstandard2.0",
      "configuration": "Debug"
    },
    "src/Extensions.Identity.Stores/Extensions.Identity.Stores.csproj": {
      "framework": "netstandard2.0",
      "configuration": "Release"
    }
}
```
